### ISSUE TITLE
Add Scholarship Sponsor: Rhino

### ISSUE THREAD

**Issue by abelmartin** [goruco/goruco2018#11]
```YAML
- name: Rhino
  css_class: rhino
  website: http://www.sayrhino.com/
  bio: “Rhino is the smart alternative to security deposits. Renters pay less up front, landlords are covered, and issues are resolved fairly, always.”
  location: New York, NY
```
![rhino](https://user-images.githubusercontent.com/29429/39633799-02348cae-4f87-11e8-9fa0-32cedaa6bbc6.jpg)
